Concreting

Concrete    1:4:8 Mix-M7.5  =    Cement-170kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:3:6 Mix-M10   =    Cement-220kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:2:4 Mix-M15   =    Cement-320kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:1.5:3 Mix-M20 =    Cement-408kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:1:2 Mix-M25   =    Cement-568kg,  Sand-0.6m3,   Aggr-1m3

Masonry

S.S.M    in  1:6            =    Cement-75kg,   Sand-0.4m3
Hollow block 20cm thick     =    Cement-6kg,    Sand-0.032m3, blocks-12.5Nos
Hollow block 10cm thick     =    Cement-6kg,    Sand-0.032m3, blocks-50 Nos

Concreting

Concrete    1:4:8 Mix-M7.5  =    Cement-170kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:3:6 Mix-M10   =    Cement-220kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:2:4 Mix-M15   =    Cement-320kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:1.5:3 Mix-M20 =    Cement-408kg,  Sand-0.6m3,   Aggr-1m3
Concrete    1:1:2 Mix-M25   =    Cement-568kg,  Sand-0.6m3,   Aggr-1m3

Masonry

S.S.M in 1:6                =    Cement-75kg,   Sand-0.4m3
Hollow block 20cm thick     =    Cement-6kg,    Sand-0.032m3, blocks-12.5Nos
Hollow block 10cm thick     =    Cement-6kg,    Sand-0.032m3, blocks-50 Nos
